export enum MethodName {
  ConnectWalletRes = "ConnectWalletRes",
  GetProfileRes = "GetProfileRes",
  ShareGameRes = "ShareGameRes",
  FollowBotRes = "FollowBotRes",
  ClaimDailyLogInRes = "ClaimDailyLogInRes",
  GetWalletAddressRes = "GetWalletAddressRes",
  IsConnectedRes = "IsConnectedRes",
  PayRes = "PayRes",
  GetPaymentRes = "GetPaymentRes",
  GetTokenBalaceRes = "GetTokenBalaceRes",
  PayWithStarsRes = "PayWithStarsRes",
  GetStarBalaceRes = "GetStarBalaceRes",
  SaveSessionToken = "SaveSessionToken",
}
